### ISSUE TITLE
developing jamovi modules using functions from outside packages

### ISSUE THREAD

**Issue by sbalci** [jamovi/jmvtools#1]
Dear @jonathon-love ,

I would like to construct a module using functions from outside packages.

I have read the guideline at _developer hub for jamovi_. I have followed the instructions and example seems to work as described.

As described in the guideline `paste` is not successful in some functions. I have gone through `jmvcore`'s _construct_ and _compose_ formulas as well.

I would like to convert this into a formula:
`arsenal::tableby(~ A + B + C)`

I have tried the following but could not go any further:

```r
formula <- jmvcore::constructFormula(terms = list(self$options$vars))
            
            formula <- paste('arsenal::tableby( ~', formula, ')')
            
            formula <- as.formula(formula)
            
            table1 <- tableone(formula, self$data)
            
            results <- summary(table1)
            
            print(results)
```

Would you please guide me which functions to use, or how to proceed?

 Best wishes

**Comment by jonathon-love** [comment]
hi,

so this code looks like it should work, however, the output (from the print statement) will appear at the console, rather than in the jamovi results panel. is that the issue you're having here? if so, take a look here (a similar example):

https://dev.jamovi.org/tuts0104-implementing-an-analysis.html

> Now this analysis will and does work; however when running in jamovi, the result of the print statement will appear at the terminal, rather than in the application’s results area (where the user would like it). To remedy this, rather than simply printing the results, we assign the results to the analysis’ results object. When run in an R session, the results will still be printed, but when run in jamovi, the results will appear in the results panel. We assign to the analysis’ result object using (you guessed it), self$results

cheers

**Comment by sbalci** [comment]
Hi,

Thank you for your response.

I think I still have a formula construction problem, probably closing bracket of formula or probably introducing the data to the function.



**This is the installation output:**
```
> jmvtools::install()

jamovi compiler

jamovi found at /Applications/jamovi.app
wrote: tableone.h.R
wrote: tableone.u.yaml
wrote: tableone.src.js
wrote: tableone.js
writing module meta
wrote: 0000.yaml
wrote: jamovi.yaml
* installing *source* package ‘SuperAwesome’ ...
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘SuperAwesome’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (SuperAwesome)
wrote module: SuperAwesome.jmo

Installing SuperAwesome.jmo
Module installed successfully
```

**These are the screenshots I get after side upload:**

_Without data:_
<img width="646" alt="without_data" src="https://user-images.githubusercontent.com/7208830/69602446-a7501100-1028-11ea-9163-95ade7462e78.png">

_With data:_
<img width="645" alt="with_data" src="https://user-images.githubusercontent.com/7208830/69602460-b20aa600-1028-11ea-9483-4e178de6c7ba.png">

_With data whole Debug:_
<img width="653" alt="debug_withdata" src="https://user-images.githubusercontent.com/7208830/69602473-bf279500-1028-11ea-8e52-8f9373169a7e.png">




**Zipped are current files:** 
_0000.yaml
DESCRIPTION
NAMESPACE
tableone.a.yaml
tableone.b.R_
[files.zip](https://github.com/jamovi/jmvtools/files/3890210/files.zip)

**Comment by jonathon-love** [comment]
try this for `ttestone.b.R`

```
tableoneClass <- if (requireNamespace('jmvcore')) R6::R6Class(
    "tableoneClass",
    inherit = tableoneBase,
    private = list(
        .run = function() {

            if (length(self$options$vars) == 0)
                return()

            formula <- jmvcore::constructFormula(terms = self$options$vars)
            formula <- paste('~', formula)
            formula <- as.formula(formula)

            table1 <- arsenal::tableby(formula, self$data)
            results <- summary(table1)

            self$results$text$setContent(results)
        })
)
```

you'll also need a `jamovi/tableone.r.yaml` (this should have been created when you did `jmvtools::addAnalysis(...)`):

```
---
name:  ttest
title: Independent Samples T-Test
jrs:   '1.1'

items:
    - name:  text
      title: Independent Samples T-Test
      type:  Preformatted 
```

let me know if you want a slack invite ... you may find these issues easier to solve over slack.

cheers

**Comment by sbalci** [comment]
Hi,
Thank you very much. Now it works. I will work on design of the table as well.
I will be happy to join slack channel: drserdarbalci@gmail.com

Best wishes

<img width="1021" alt="Ekran Resmi 2019-11-26 11 21 42" src="https://user-images.githubusercontent.com/7208830/69611580-251f1700-103f-11ea-9035-f8413faea6f0.png">
