### ISSUE TITLE
Dependency 'node' is not available for 'jmvtools'

### ISSUE THREAD

**Issue by easauleau** [jamovi/jmvtools#2]
Hi Jonathon-love,
I would like to develop a simple Bayesian descriptive module for jamovi but when I tried to install jmvtools, I got the ERROR: dependency 'node' is not available for package 'jmvtools'.
I have no idea how to fix it..
A little help?
Thanks Erik

**Comment by jonathon-love** [comment]
hi,

apologies for the delay, i've been moving house. are you installing as per the instructions here?:

https://dev.jamovi.org/tuts0101-getting-started.html

kind regards

**Comment by easauleau** [comment]
of course not! My apologies. Now it works fine (see my first .jmo toy, it is in French because for students). 
Two questions remain: 
-internationalisation? for é, à, ... 
-i would like to implement this "MyBayes" modules with two items "description for binary variable" (done in the joint code) and a second in the menu "description for continuous variables". How can I do that? 

thanks in advance. Erik 


De: "Jonathon Love" <notifications@github.com> 
À: "jamovi/jmvtools" <jmvtools@noreply.github.com> 
Cc: "SAULEAU Eric-Andre (01D15)" <ea.sauleau@unistra.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 10 Février 2020 00:57:44 
Objet: Re: [jamovi/jmvtools] Dependency 'node' is not available for 'jmvtools' (#2) 



hi, 

apologies for the delay, i've been moving house. are you installing as per the instructions here?: 

[ https://dev.jamovi.org/tuts0101-getting-started.html | https://dev.jamovi.org/tuts0101-getting-started.html ] 

kind regards

**Comment by jonathon-love** [comment]
wrt é, à, where abouts did you want to put them? you should just be able to put them, as-is, into the .yaml files. i think you can just put them as-is into the .R files too, not sure.

wrt menus, if i understand correctly, you can add menu stuff into the .a.yaml file. i.e.:

```
menuGroup: Frequencies
menuSubgroup: One Sample Proportion Tests
menuTitle: 2 Outcomes
menuSubtitle: Binomial test
```

jmv serves as a pretty good example for a lot of stuff:

https://github.com/jamovi/jmv/blob/master/jamovi/proptest2.a.yaml

cheers

**Comment by sjentsch** [comment]
You should perhaps close it, it is solved.

**Comment by karchjd** [comment]
I am actually having the same problem, while trying to update my module. `install.packages('jmvtools', repos='https://repo.jamovi.org')` and `install.packages('jmvtools', repos=c('https://repo.jamovi.org', 'https://cran.r-project.org'))` both fail with `ERROR: dependency ‘node’ is not available for package ‘jmvtools’. This is my system

```
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.1.1
```

**Comment by karchjd** [comment]
Update: Was just running into a timeout `options(timeout = 600)` before the install command solved it.

**Comment by jonathon-love** [comment]
yeah, R provides quite the red-herring error message here.
